name: Lint markdown

on:
  push:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v27
      - name: Lint document
        run: |
          npx zx scripts/lint.mjs
        env: 
          MARKDOWN_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
